### ISSUE TITLE
Add Readme.md

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-chat#12]
We need to create readme file as in the LaravelMedia package https://github.com/RonasIT/laravel-media

**Comment by milliyin** [comment]
Hey! I can help you make this README.md file. Assign this to me.

**Comment by DenTray** [comment]
@milliyin thanks! Please proceed

**Comment by milliyin** [comment]
Just wana confirm are you talking about [readme.md](https://github.com/RonasIT/laravel-media/blob/master/readme.md) or this [Rep](https://github.com/RonasIT/laravel-chat)

**Comment by DenTray** [comment]
@milliyin Readme.md file should be created in this rep with the similar strucrure as in the LaravelMedia packge I've mentioned in description

**Comment by DenTray** [comment]
@milliyin thanks!
