### ISSUE TITLE
Ability to register package routes in required place of the app

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-chat#16]
At the moment all package endpoints are registering automatically after package installation.

It good, but we can't wrap it into middlewares or modify prefixes.

Good solution to resolve it - will be implement some kind of helper which will register routes in required place.

As a reference - we can implement the same logic as Laravel providing in Auth::routes() method.

It also will be very helpful if the package will automatically determine whether he should register routes automatically (if a helper didn't call) or not.

**Comment by RGO230** [comment]
@DenTray, done. Please check

**Comment by DenTray** [comment]
@RGO230 as discussed, please check my case described in the similar task in media package and make the same changes here

**Comment by DenTray** [comment]
Released in 0.0.2-beta
