### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-chat#23]
Need to make readme file more interactive as it was implemented in Laravel media package

1. Make 1 and 2 points copyable
2. Provide an ability to publish package's resources using it service provider

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by yogyrton** [comment]
@DenTray Done

**Comment by DenTray** [comment]
@yogyrton looks good! Thanks!
